services:

  backend:
    build: ./backend
    container_name: signwhispers-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env     # .env is inside the backend folder
    restart: always

  frontend:
    build: ./frontend
    container_name: signwhispers-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
