# version: '3.8'

# services:

#   backend:
#     build: ./backend
#     container_name: signwhispers-backend
#     ports:
#       - "8000:8000"
#     environment:
    
#       - MONGO_URI= mongodb+srv://fatimashahzad3470_db_user:GQrNQI1GfF83lcLZ@cluster0.lihr8au.mongodb.net/signwhisperdb
#     restart: always

#   frontend:
#     build: ./frontend
#     container_name: signwhispers-frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     restart: always




# version: '3.8'

# services:

#   backend:
#     build: ./backend
#     container_name: signwhispers-backend
#     ports:
#       - "8000:8000"
#     env_file:
#       - .env          # reads ALL variables from your .env file automatically
#     restart: always

#   frontend:
#     build: ./frontend
#     container_name: signwhispers-frontend
#     ports:
#       - "80:80"
#     depends_on:
#       - backend
#     restart: always




services:

  backend:
    build: ./backend
    container_name: signwhispers-backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env     # .env is inside the backend folder
    restart: always

  frontend:
    build: ./frontend
    container_name: signwhispers-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always